name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Build release zip
        run: zip -r ha-alias-manager.zip ha-alias-manager.js translations/

      - name: Upload zip to release
        run: gh release upload ${{ github.event.release.tag_name }} ha-alias-manager.zip --clobber
        env:
          GH_TOKEN: ${{ github.token }}
